name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod tidy

      - name: Build binary
        run: go build -o homelab_agent

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: homelab_agent
          path: ./homelab_agent

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: homelab_agent

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: homelab_agent
          token: ${{ secrets.CUSTOM_GH_TOKEN }}
